In [20]:
label_lst = [
    # "maximum_sharpe_ratio",
    "monte_carlo_cholesky",
]

In [21]:
import warnings
warnings.filterwarnings("ignore")

from pathlib import Path
import pandas as pd
import numpy as np
from datetime import datetime
from dateutil.rrule import rrule, MONTHLY, WEEKLY, MO, TU, WE, TH, FR

np.random.seed(134)
pd.set_option('display.max_columns', None)  
pd.options.display.max_rows = 999


july_2021 = [
#     'MONDAY',   'TUESDAY',   'WEDNESDAY',  'THURSDAY',     'FRIDAY'
#  |------------|-------------|-------------|-------------|--------------|
                                '2021-07-14', '2021-07-15', '2021-07-16',
    '2021-07-19', '2021-07-20', '2021-07-21', '2021-07-22', '2021-07-23',
    '2021-07-26', '2021-07-27',               '2021-07-29', '2021-07-30',
]

august_2021 = [
#     'MONDAY',   'TUESDAY',   'WEDNESDAY',  'THURSDAY',     'FRIDAY'
#  |------------|-------------|--------------|-------------|--------------|
    '2021-08-02', '2021-08-03', '2021-08-04', '2021-08-05', '2021-08-06',
    '2021-08-09', '2021-08-10',                             '2021-08-13',
    '2021-08-16',                                           '2021-08-20',
    '2021-08-23',                             '2021-08-26', '2021-08-27',
                  '2021-08-31',
]

september_2021 = [
#     'MONDAY',   'TUESDAY',   'WEDNESDAY',  'THURSDAY',     'FRIDAY'
#  |------------|-------------|-------------|-------------|--------------|
                                              '2021-09-02', '2021-09-03',
                                '2021-09-08', '2021-09-09', '2021-09-10',
    '2021-09-13', '2021-09-14', '2021-09-15', '2021-09-16', '2021-09-17',
                #   '2021-09-21', '2021-09-22', '2021-09-23', '2021-09-24',
    # '2021-09-27', '2021-09-28',
]

october_2021 = [
#     'MONDAY',   'TUESDAY',   'WEDNESDAY',  'THURSDAY',     'FRIDAY'
#  |------------|-------------|-------------|-------------|--------------|
                                                            '2021-10-01',
    '2021-10-04', '2021-10-05', '2021-10-06', '2021-10-07', '2021-10-08',
    '2021-10-11',               '2021-10-13', '2021-10-14', '2021-10-15',
    '2021-10-18', '2021-10-19', '2021-10-20', '2021-10-21', '2021-10-22',
    '2021-10-25',               '2021-10-27',               '2021-10-29',
]

november_2021 = [
#     'MONDAY',   'TUESDAY',   'WEDNESDAY',  'THURSDAY',     'FRIDAY'
#  |------------|-------------|-------------|-------------|--------------|
    '2021-11-01', '2021-11-02', '2021-11-03',               '2021-11-05',
                                '2021-11-10', '2021-11-11', '2021-11-12',
    '2021-11-15', '2021-11-16', '2021-11-17', '2021-11-18', '2021-11-19',
                  '2021-11-23', '2021-11-24', '2021-11-25', '2021-11-26',
]

december_2021 = [
#     'MONDAY',   'TUESDAY',   'WEDNESDAY',  'THURSDAY',     'FRIDAY'
#  |------------|-------------|-------------|-------------|--------------|
                                '2021-12-01', '2021-12-02', '2021-12-03',
    '2021-12-06', '2021-12-07', '2021-12-08', '2021-12-09', '2021-12-10',
    '2021-12-13', '2021-12-14', '2021-12-15', '2021-12-16', '2021-12-17',
    '2021-12-20', '2021-12-21',                             '2021-12-24',
]

january_2022 = [
#     'MONDAY',   'TUESDAY',   'WEDNESDAY',  'THURSDAY',     'FRIDAY'
#  |------------|-------------|-------------|-------------|--------------|
    '2022-01-03', '2022-01-04', '2022-01-05', '2022-01-06', '2022-01-07',
    '2022-01-10', '2022-01-11', '2022-01-12', '2022-01-13', '2022-01-14',
                  '2022-01-18', '2022-01-19', '2022-01-20', '2022-01-21',
                                '2022-01-26', '2022-01-27', '2022-01-28',
]

february_2022 = [
#     'MONDAY',   'TUESDAY',   'WEDNESDAY',  'THURSDAY',     'FRIDAY'
#  |------------|-------------|-------------|-------------|--------------|
                                                            '2022-02-04',
    '2022-02-07',               '2022-02-09', '2022-02-10', '2022-02-11',
    '2022-02-14', '2022-02-15', '2022-02-16',               '2022-02-18',
                  '2022-02-22', '2022-02-23', '2022-02-24', '2022-02-25',
]

march_2022 = [
#     'MONDAY',   'TUESDAY',   'WEDNESDAY',  'THURSDAY',     'FRIDAY'
#  |------------|-------------|-------------|-------------|--------------|
                 '2022-03-01',                              '2022-03-04',
    '2022-03-07', '2022-03-08', '2022-03-09', '2022-03-10', '2022-03-11',    
]


all_dates_list = [
    july_2021,
    august_2021,
    september_2021,
    # october_2021, 
    # november_2021,
    # december_2021,
    # january_2022,
    # february_2022,
    # march_2022,
]

days = []
for date_lists in all_dates_list:
    days += date_lists

In [22]:


def build_days(key1):
    start_date = datetime(2021, 7, 14)
    temp = list(rrule(freq=WEEKLY, byweekday=key1, count=35, dtstart=start_date))
    days_list = []
    for i in temp:
        days_list.append(str(i)[:10])
    return days_list


report_df = pd.DataFrame()

for day in days:
    month = str(day)[:7]
    path9 = Path(f"/home/gdp/russell_3k/reports/port_results/{month}/{day}/one_{label_lst[0]}.csv")
    df0 = pd.DataFrame(pd.read_csv(path9)[['date','portfolio']]).round(2)
    df0.columns = ['exit_date','portfolio'] 

    investment = df0['portfolio'].iloc[0]
    max1 = df0['portfolio'].iloc[0]
    up10_goal = max1 * 1.1
    down10_sell = max1 * 0.895
    new_max = []
    for i in df0['portfolio']:
        if i > max1:
            max1 = i
            new_max.append(i)
        else:
            new_max.append(max1)

    new_loss = []
    for i in df0['portfolio']:
        if i < max1:
            max1 = i
            new_loss.append(i)
        else:
            new_loss.append(max1)            

    df0['max'] = new_max
    df0['min'] = new_loss
    df0['max_ret'] = df0['max'] / investment
    df0['max_los'] = df0['min'] / investment
    df0['up10'] = df0['portfolio'] > up10_goal
    df0['down10'] = df0['portfolio'] < down10_sell
    df0['returns'] = ((df0['portfolio'] - investment) / investment) * 100
    df0['down_from_max'] = df0['portfolio'] / df0['max']
    df0['drop'] = df0['down_from_max'] < 0.985
    df0['over20'] = df0['returns'] >= 25.0
    up20 = df0[df0['over20'] == True]

    up10 = df0.query(f"up10 == {True}")
    up10 = up10[up10['drop'] == True]
    down10 = df0.query(f"down10 == {True}")

    if not up20.empty:
        fin = pd.DataFrame(up20.head(1).copy())
        res1 = 'W'
    
    elif not up10.empty and not down10.empty:    
        try:
            if up10.iloc[0]['exit_date'] < down10.iloc[0]['exit_date']:
                fin = pd.DataFrame(up10.head(1).copy())
                res1 = 'W'
            else:
                fin = pd.DataFrame(down10.head(1).copy())
                res1 = 'L'
        except Exception:
            print(day, '1')                
        
    elif not up10.empty:        
        try:
            fin = pd.DataFrame(up10.head(1).copy())
            res1 = 'W'
        except Exception:
            print(day, '2')

    elif not down10.empty:
        try:
            fin = pd.DataFrame(down10.head(1).copy())
            res1 = 'L'
        except Exception:
            print(day, '3')
                    
    else:
        fin = pd.DataFrame(df0.tail(1).copy())
        res1 = 'N'
            
    fin['result'] = res1
    fin.insert(loc=0, column='investment_date', value=day)
    fin.insert(loc=2, column='investment', value=investment)
    report_df = report_df.append(fin)
                
df = pd.DataFrame(report_df.copy())

mondays=build_days(MO)
tuesdays=build_days(TU)
wednesdays=build_days(WE)
thursdays=build_days(TH)
fridays=build_days(FR)

matrix = []
for i in df['investment_date']:
    if i in mondays:
        matrix.append('M')
    elif i in tuesdays:
        matrix.append('T')
    elif i in wednesdays:
        matrix.append('W')                
    elif i in thursdays:
        matrix.append('Th')
    elif i in fridays:
        matrix.append('F')
    else:
        matrix.append('-')
idx = 1
new_col = matrix
df.insert(loc=idx, column='day', value=new_col)
df = df.set_index('day').round(2)  

del df['down_from_max']
del df['drop']
del df['up10']
del df['down10']

df['gl'] = df['portfolio'] - df['investment']

df.to_csv(f"reports/score_sheet/printin_press_{label_lst[0]}.csv")
temp = pd.DataFrame(df.copy()).reset_index()
# print(df['gl'].sum())


investment = round(df['investment'].sum(),2)
exit_total = round(df['gl'].sum(),2) + investment

print("\n", df['result'].describe(), "\n")
print(f"total_investment = {'${:,.2f}'.format(investment)}")
print(f"total_exit_position = {'${:,.2f}'.format(exit_total)}")
print(f"total_return = {'{:,.2f}%'.format(((exit_total-investment)/investment)*100)}", "\n")

results_lst = list(df['result'])
total = len(results_lst)
wins = results_lst.count('W')
losses = results_lst.count('L')
neutral = results_lst.count('N')
print(
    f"Total = {total} \n\
    > Wins = {wins}, [{round(wins/total,2)}] \n\
    > Losses = {losses}, [{round(losses/total,2)}] \n\
    > Neutral = {neutral}, [{round(neutral/total,2)}]"
)

fd = df[df['result'] != 'N']
results_lst = list(fd['result'])
total = len(results_lst)
wins = results_lst.count('W')
losses = results_lst.count('L')
neutral = results_lst.count('N')
print(f"\nTotal = {total} \n\
    > Wins = {wins}, [{round(wins/total,2)}] \n\
    > Losses = {losses}, [{round(losses/total,2)}] \n\
    > Neutral = {neutral}, [{round(neutral/total,2)}]"
)

 count     36
unique     3
top        W
freq      21
Name: result, dtype: object

total_investment = $90,000.00
total_exit_position = $93,246.06
total_return = 3.61%

Total = 36
    > Wins = 21, [0.58]
    > Losses = 12, [0.33]
    > Neutral = 3, [0.08]

Total = 33
    > Wins = 21, [0.64]
    > Losses = 12, [0.36]
    > Neutral = 0, [0.0]

In [23]:
df

,investment_date,exit_date,investment,portfolio,max,min,max_ret,max_los,returns,over20,result,gl
day,,,,,,,,,,,,
W,2021-07-14,2021-09-08,2500.0,2770.52,2823.48,2453.01,1.13,0.98,10.82,False,W,270.52
Th,2021-07-15,2021-09-07,2500.0,2803.27,2846.06,2462.02,1.14,0.98,12.13,False,W,303.27
F,2021-07-16,2021-09-07,2500.0,2772.41,2817.26,2500.00,1.13,1.00,10.90,False,W,272.41
M,2021-07-19,2021-12-09,2500.0,2751.88,2795.48,2485.48,1.12,0.99,10.08,False,W,251.88
T,2021-07-20,2022-03-11,2500.0,2323.71,2769.19,2241.23,1.11,0.90,-7.05,False,N,-176.29
W,2021-07-21,2021-11-02,2500.0,2935.11,3009.40,2394.26,1.20,0.96,17.40,False,W,435.11
Th,2021-07-22,2021-10-04,2500.0,2233.60,2505.80,2233.60,1.00,0.89,-10.66,False,L,-266.40
F,2021-07-23,2021-11-16,2500.0,3157.89,3157.89,2499.99,1.26,1.00,26.32,True,W,657.89
M,2021-07-26,2021-11-22,2500.0,2795.16,2903.98,2411.21,1.16,0.96,11.81,False,W,295.16
T,2021-07-27,2021-11-22,2500.0,2782.34,2880.92,2427.78,1.15,0.97,11.29,False,W,282.34
Th,2021-07-29,2021-10-27,2500.0,2765.63,2852.44,2412.10,1.14,0.96,10.63,False,W,265.63
F,2021-07-30,2021-10-18,2500.0,3278.08,3278.08,2401.38,1.31,0.96,31.12,True,W,778.08
M,2021-08-02,2021-11-05,2500.0,2779.14,2861.24,2397.83,1.14,0.96,11.17,False,W,279.14
T,2021-08-03,2021-11-22,2500.0,2803.93,2898.42,2401.48,1.16,0.96,12.16,False,W,303.93
W,2021-08-04,2022-01-19,2500.0,2228.26,2701.56,2228.26,1.08,0.89,-10.87,False,L,-271.74
Th,2021-08-05,2022-01-26,2500.0,2215.21,2783.66,2215.21,1.11,0.89,-11.39,False,L,-284.79
F,2021-08-06,2021-11-22,2500.0,2790.16,2875.31,2388.92,1.15,0.96,11.61,False,W,290.16
M,2021-08-09,2022-03-11,2500.0,2295.26,2720.19,2261.49,1.09,0.90,-8.19,False,N,-204.74
T,2021-08-10,2022-02-23,2500.0,2231.54,2718.63,2231.54,1.09,0.89,-10.74,False,L,-268.46
F,2021-08-13,2022-01-20,2500.0,2200.29,2778.76,2200.29,1.11,0.88,-11.99,False,L,-299.71
M,2021-08-16,2022-03-11,2500.0,2244.13,2784.57,2241.76,1.11,0.90,-10.23,False,N,-255.87
F,2021-08-20,2021-11-10,2500.0,2905.47,2966.53,2353.77,1.19,0.94,16.22,False,W,405.47
M,2021-08-23,2021-11-24,2500.0,2778.04,2838.08,2330.21,1.14,0.93,11.12,False,W,278.04
Th,2021-08-26,2022-02-23,2500.0,2210.08,2746.98,2210.08,1.10,0.88,-11.60,False,L,-289.92
F,2021-08-27,2021-11-10,2500.0,2770.78,2830.17,2335.27,1.13,0.93,10.83,False,W,270.78
T,2021-08-31,2022-02-17,2500.0,2223.36,2751.99,2223.36,1.10,0.89,-11.07,False,L,-276.64
Th,2021-09-02,2022-01-19,2500.0,2232.05,2610.05,2232.05,1.04,0.89,-10.72,False,L,-267.95
F,2021-09-03,2022-03-11,2500.0,2228.42,2671.85,2228.42,1.07,0.89,-10.86,False,L,-271.58
W,2021-09-08,2022-01-13,2500.0,2232.12,2514.65,2232.12,1.01,0.89,-10.72,False,L,-267.88
Th,2021-09-09,2022-01-19,2500.0,2208.67,2657.07,2208.67,1.06,0.88,-11.65,False,L,-291.33
F,2021-09-10,2021-11-09,2500.0,2763.07,2805.73,2352.54,1.12,0.94,10.52,False,W,263.07
M,2021-09-13,2021-11-10,2500.0,2913.69,2999.11,2329.09,1.20,0.93,16.55,False,W,413.69
T,2021-09-14,2022-01-18,2500.0,2229.81,2569.11,2229.81,1.03,0.89,-10.81,False,L,-270.19
W,2021-09-15,2021-11-09,2500.0,2759.47,2814.37,2295.97,1.13,0.92,10.38,False,W,259.47
Th,2021-09-16,2021-11-10,2500.0,2815.41,2894.67,2315.73,1.16,0.93,12.62,False,W,315.41
F,2021-09-17,2021-11-09,2500.0,2818.10,2885.30,2271.31,1.15,0.91,12.72,False,W,318.10

In [24]:
mondays = pd.DataFrame(temp[temp.day == 'M'])
# print(mondays.describe().round(2),'\n')

mon = mondays[mondays['result'] != 'N']
results_lst = list(mon['result'])
total = len(results_lst)
wins = results_lst.count('W')
losses = results_lst.count('L')
neutral = results_lst.count('N')
print(
    f"Total = {total} \n\
    > Wins = {wins}, [{round(wins/total,2)}] \n\
    > Losses = {losses}, [{round(losses/total,2)}] \n\
    > Neutral = {neutral}, [{round(neutral/total,2)}]"
)
# print(f"Total GL = {mondays['gl'].sum()}")
# print(f"Total GL % = {mondays['gl'].sum() / mondays['investment'].sum()}")

mondays.set_index('day', inplace=True)
mondays.to_csv(f'reports/score_sheet/mondays_{label_lst[0]}.csv')
# mondays

Total = 5
    > Wins = 5, [1.0]
    > Losses = 0, [0.0]
    > Neutral = 0, [0.0]

In [25]:
tuesdays = pd.DataFrame(temp[temp.day == 'T'])
# print(tuesdays.describe().round(2),'\n')

tue = tuesdays[tuesdays['result'] != 'N']
results_lst = list(tue['result'])
total = len(results_lst)
wins = results_lst.count('W')
losses = results_lst.count('L')
neutral = results_lst.count('N')
print(
    f"Total = {total} \n\
    > Wins = {wins}, [{round(wins/total,2)}] \n\
    > Losses = {losses}, [{round(losses/total,2)}] \n\
    > Neutral = {neutral}, [{round(neutral/total,2)}]"
)
tuesdays.set_index('day', inplace=True)
tuesdays.to_csv(f'reports/score_sheet/tuesdays_{label_lst[0]}.csv')
# tuesdays

Total = 5
    > Wins = 2, [0.4]
    > Losses = 3, [0.6]
    > Neutral = 0, [0.0]

In [26]:
wednesdays = pd.DataFrame(temp[temp.day == 'W'])
# print(wednesdays.describe().round(2),'\n')

wed = wednesdays[wednesdays['result'] != 'N']
results_lst = list(wed['result'])
total = len(results_lst)
wins = results_lst.count('W')
losses = results_lst.count('L')
neutral = results_lst.count('N')
print(
    f"Total = {total} \n\
    > Wins = {wins}, [{round(wins/total,2)}] \n\
    > Losses = {losses}, [{round(losses/total,2)}] \n\
    > Neutral = {neutral}, [{round(neutral/total,2)}]"
)

wednesdays.set_index('day',inplace=True)
wednesdays.to_csv(f'reports/score_sheet/wednesdays_{label_lst[0]}.csv')
# wednesdays

Total = 5
    > Wins = 3, [0.6]
    > Losses = 2, [0.4]
    > Neutral = 0, [0.0]

In [27]:
thursdays = pd.DataFrame(temp[temp['day'] == 'Th'])
# print(thursdays.describe().round(2),'\n')

thur = thursdays[thursdays['result'] != 'N']
results_lst = list(thur['result'])
total = len(results_lst)
wins = results_lst.count('W')
losses = results_lst.count('L')
neutral = results_lst.count('N')
print(
    f"Total = {total} \n\
    > Wins = {wins}, [{round(wins/total,2)}] \n\
    > Losses = {losses}, [{round(losses/total,2)}] \n\
    > Neutral = {neutral}, [{round(neutral/total,2)}]"
)

thursdays.set_index('day',inplace=True)
thursdays.to_csv(f'reports/score_sheet/thursdays_{label_lst[0]}.csv')
# thursdays

Total = 8
    > Wins = 3, [0.38]
    > Losses = 5, [0.62]
    > Neutral = 0, [0.0]

In [28]:
fridays = pd.DataFrame(temp[temp.day == 'F'])
# print(fridays.describe().round(2),'\n')

fri = fridays[fridays['result'] != 'N']
results_lst = list(fri['result'])
total = len(results_lst)
wins = results_lst.count('W')
losses = results_lst.count('L')
neutral = results_lst.count('N')
print(
    f"Total = {total} \n\
    > Wins = {wins}, [{round(wins/total,2)}] \n\
    > Losses = {losses}, [{round(losses/total,2)}] \n\
    > Neutral = {neutral}, [{round(neutral/total,2)}]"
)

fridays.set_index('day',inplace=True)
fridays.to_csv(f'reports/score_sheet/fridays_{label_lst[0]}.csv')
# fridays

Total = 10
    > Wins = 8, [0.8]
    > Losses = 2, [0.2]
    > Neutral = 0, [0.0]

In [29]:
# print(mondays.describe().round(2),'\n')
# print(tuesdays.describe().round(2),'\n')
# print(wednesdays.describe().round(2),'\n')
# print(thursdays.describe().round(2),'\n')
# print(fridays.describe().round(2),'\n')

In [30]:
losers_lst_df = df[df['result'] == 'L']
losers_lst_df.to_csv(f'reports/score_sheet/losers_lst_{label_lst[0]}.csv')
print(f"COUNT: {len(losers_lst_df)}")
print(round(losers_lst_df.returns.mean(),2))

losers_lst_df

COUNT: 12
-11.09

,investment_date,exit_date,investment,portfolio,max,min,max_ret,max_los,returns,over20,result,gl
day,,,,,,,,,,,,
Th,2021-07-22,2021-10-04,2500.0,2233.60,2505.80,2233.60,1.00,0.89,-10.66,False,L,-266.40
W,2021-08-04,2022-01-19,2500.0,2228.26,2701.56,2228.26,1.08,0.89,-10.87,False,L,-271.74
Th,2021-08-05,2022-01-26,2500.0,2215.21,2783.66,2215.21,1.11,0.89,-11.39,False,L,-284.79
T,2021-08-10,2022-02-23,2500.0,2231.54,2718.63,2231.54,1.09,0.89,-10.74,False,L,-268.46
F,2021-08-13,2022-01-20,2500.0,2200.29,2778.76,2200.29,1.11,0.88,-11.99,False,L,-299.71
Th,2021-08-26,2022-02-23,2500.0,2210.08,2746.98,2210.08,1.10,0.88,-11.60,False,L,-289.92
T,2021-08-31,2022-02-17,2500.0,2223.36,2751.99,2223.36,1.10,0.89,-11.07,False,L,-276.64
Th,2021-09-02,2022-01-19,2500.0,2232.05,2610.05,2232.05,1.04,0.89,-10.72,False,L,-267.95
F,2021-09-03,2022-03-11,2500.0,2228.42,2671.85,2228.42,1.07,0.89,-10.86,False,L,-271.58
W,2021-09-08,2022-01-13,2500.0,2232.12,2514.65,2232.12,1.01,0.89,-10.72,False,L,-267.88
Th,2021-09-09,2022-01-19,2500.0,2208.67,2657.07,2208.67,1.06,0.88,-11.65,False,L,-291.33
T,2021-09-14,2022-01-18,2500.0,2229.81,2569.11,2229.81,1.03,0.89,-10.81,False,L,-270.19

In [31]:
neutral_lst_df = df[df['result'] == 'N']
neutral_lst_df.to_csv(f'reports/score_sheet/neutral_lst_{label_lst[0]}.csv')
print(f"COUNT: {len(neutral_lst_df)}")
print(round(neutral_lst_df.returns.mean(),2))
neutral_lst_df

COUNT: 3
-8.49

,investment_date,exit_date,investment,portfolio,max,min,max_ret,max_los,returns,over20,result,gl
day,,,,,,,,,,,,
T,2021-07-20,2022-03-11,2500.0,2323.71,2769.19,2241.23,1.11,0.9,-7.05,False,N,-176.29
M,2021-08-09,2022-03-11,2500.0,2295.26,2720.19,2261.49,1.09,0.9,-8.19,False,N,-204.74
M,2021-08-16,2022-03-11,2500.0,2244.13,2784.57,2241.76,1.11,0.9,-10.23,False,N,-255.87

In [32]:
winner_lst_df = df[df['result'] == 'W']
winner_lst_df.to_csv(f'reports/score_sheet/winner_lst_{label_lst[0]}.csv')
print(f"COUNT: {len(winner_lst_df)}")
print(round(winner_lst_df.returns.mean(),2))
# winner_lst_df

COUNT: 21
13.73